# 模型列表：https://help.aliyun.com/zh/model-studio/getting-started/models
[litellm_qwen_plus]
model="openai/qwen-plus"
api_base = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "<你的阿里云百炼平台的token>"

[openai_qwen_plus]
model="qwen-plus"
api_base = "https://dashscope.aliyuncs.com/compatible-mode/v1"
api_key = "<你的阿里云百炼平台的token>"
